# Generated by Django 3.1.3 on 2020-11-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default='UHl0aG9uIGlzIGZ1bg==', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
