# Generated by Django 3.1.3 on 2020-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20201130_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default='57ef1531092a457f96d9e33eeb0875ac', max_length=32, primary_key=True, serialize=False),
        ),
    ]
