# Generated by Django 3.1.3 on 2020-11-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201130_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(default='0611fbd3a50143cdb9eeaccba752a35f', max_length=32, primary_key=True, serialize=False),
        ),
    ]
