# Generated by Django 3.1.3 on 2020-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20201130_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_bookmarked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
